### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by patte** [phauer/migrate-itunes-to-rhythmbox#1]
Thank you for your work on this promising package!
Sadly I can't get it to work, neither playlists nor counts-ratings. I get the following error:

```
patte@hst:~$ migrate-itunes-to-rhythmbox playlists --itunes_library_xml="~/syncthings/Library.xml" --rhythmbox_playlists_xml="~/.local/share/rhythmbox/playlists.xml" --source_library_root="/Volumes/T3/Music/"
Root path path of the Rhythmbox-based library. [/home/patte/Music]: 
Reading iTunes library in /home/patte/syncthings/Library.xml
Creating Rhythmbox playlist in /home/patte/.local/share/rhythmbox/playlists.xml
Traceback (most recent call last):
  File "/home/patte/.local/bin/migrate-itunes-to-rhythmbox", line 72, in <module>
    cli()
  File "/home/patte/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/patte/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/patte/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/patte/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/patte/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/patte/.local/bin/migrate-itunes-to-rhythmbox", line 39, in migrate_playlist
    exclude_playlist_folders=exclude_playlist_folders)
  File "/home/patte/.local/lib/python3.5/site-packages/migrate_itunes_to_rhythmbox/rhythmbox_playlists_writer.py", line 34, in write
    transformed_location = transform_to_rhythmbox_path(song.location_escaped, target_library_root, source_library_root)
  File "/home/patte/.local/lib/python3.5/site-packages/migrate_itunes_to_rhythmbox/transform.py", line 19, in transform_to_rhythmbox_path
    replaced_location = location_escaped\
AttributeError: 'NoneType' object has no attribute 'replace'
```

Maybe the iTunes path is a problem: I had my iTunes library on an external disk. The first few lines of my library look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Major Version</key><integer>1</integer>
    <key>Minor Version</key><integer>1</integer>
    <key>Date</key><date>2016-09-27T15:40:57Z</date>
    <key>Application Version</key><string>12.5.1.21</string>
    <key>Features</key><integer>5</integer>
    <key>Show Content Ratings</key><true/>
    <key>Music Folder</key><string>file:///Users/patte/Music/iTunes/iTunes%20Media/</string>
    <key>Library Persistent ID</key><string>REMOVED</string>
    <key>Tracks</key>
    <dict>
        <key>5980</key>
        <dict>
            <key>Track ID</key><integer>5980</integer>
            <key>Name</key><string>Think</string>
            <key>Artist</key><string>Aretha Franklin</string>
            ...
            <key>Location</key><string>file:///Volumes/T3/Music/iTunes/iTunes%20Music/Aretha%20Franklin/The%20Best%20of%20Arentha%20Franklin/19%20Think.mp3</string>
        </dict>
```

Any help would be much appreciated!

**Comment by phauer** [comment]
Thanks for your feedback. Could you provide me with more information, please?

Does `$ pip3 freeze | grep pyItunes` return `pyItunes==1.4`?

Can you spot tracks in your iTunes xml without a Location? That means a `<dict>` entry of `Tracks` without  a `<key>Location</key><string>path</string>`?

Can you attach a (minimal) iTunes xml that leads to this error? This would make investigation and fixing much easier.

**Comment by patte** [comment]
Thank you for your fast reply phauer!
Yes, I get `pyItunes==1.4`
My Library.xml is huge (27 MB), hard to say if it misses a Location. But if you'd have time to inspect it, I uploaded it here: https://owncloud.pa.tte.io/index.php/s/xOMXQhOQr2uddqt
Thank you so much!

**Comment by phauer** [comment]
You have songs in your iTunes Library without a file location. They are all of type "remote" - whatever that means. Some have a "purchased" flag set to true. Some have a "matched" flag set to true. 

Anyway, I just uploaded version 1.0.1 which should fix this issue. It will now skip these songs, because they can't be processed anyway. Rhythmbox uses the location as the identifier for a song. If there is no location, Rhythmbox can't assign the playlist song to the song in the Rhythmbox library. 
The script will tell you which songs have been skipped so you can investigate at your own. 

Please uninstall 1.0.0, install version 1.0.1 and give me some feedback.

**Comment by patte** [comment]
YES! It worked. Thank you very much! Nice work!

Just a small issue, I noticed when importing playlists. In case the --target_library_root is not given, the library suggests: `Root path path of the Rhythmbox-based library. [/home/patte/Music]:` If I take this default, the resulting paths in playlist.xml miss the separating /
If I use /home/patte/Music**/** everything works fine.

see playlist asdf
rhythmbox/playlists.xml

```
<?xml version="1.0"?>
<rhythmdb-playlists>
  <playlist browser-position="231" name="Audiobooks" search-type="search-match" show-browser="true" type="static"/>
  <playlist browser-position="231" name="Tones" search-type="search-match" show-browser="true" type="static">
    <location>file:///Users/patte/Music/iTunes/iTunes%20Media/Ringtones/CTU%20Intercom.m4r</location>
  </playlist>
  <playlist browser-position="231" name="asdf" search-type="search-match" show-browser="true" type="static">
    <location>file:///home/patte/MusiciTunes/iTunes%20Music/Elvis%20Presley/The%20Essential_%20Elvis%20Presley/2-14%20Return%20to%20Sender.m4p</location>
  </playlist>

```

**Comment by patte** [comment]
Alright, playlists worked fine! But I just notices, the playcounts didn't end up in rhythmbox somehow, altough I see them in Library.xml I only have play counts "Never" in rhythmbox. Is there a warning when you can't match a file? This is the command I used:

```
migrate-itunes-to-rhythmbox counts-ratings --itunes_library_xml="~/syncthings/Library.xml" --source_library_root="/Volumes/T3/Music/" --target_library_root="/home/patte/Music/" --rhythmdb="~/.local/share/rhythmbox/rhythmdb.xml"
```

Is my --source_library_root correct?

**Comment by phauer** [comment]
Thanks again for your valuable feedback.
- Wrong default value `target_library_root`: You're right. Fixed. But yet unreleased.
- Print a warning if no path matches: Good idea. I'll implement that.
- Missing ratings: That needs to be fixed. But we should open a new issue for this. I suppose that's because your files are located on an external volume. So your iTunes paths are something like `file:///Volumes/T3/Music/` and not `file://localhost/D:/Music/`. I'll add support for external devices. Just give me some time. 

If you are in hurry, you can replace all occurrences of `file:///Volumes/T3/Music/` in your iTunes Library with `file://localhost/T3/Music/`. If you now use `T3/Music/` as the source_library_root it should work. But that's hacked. If you can wait a little bit I would very appreciate it if you test my solution. :-)

`T3` is the name of your external device, isn't it?

**Comment by patte** [comment]
Glad if I can help.
Yes you're right, T3 is the name of my external storage. Ok, now I understand what the problem is, you are matching against `localhost`, which you have when the library resides on the main storage. I'll try to replace the paths, to be able to get going with rhythmbox. But let me know as soon as you implemented the fix and I'll test it.

EDIT: And indeed it worked by hacking Library.xml, you sir, made my day! Thanks.

**Comment by phauer** [comment]
That's great, Patrick. I'm happy to hear this.
- I added some regression tests for this bug
- The script now prints a helpful warning if no song was enriched with the play count and rating.

I created issue #2 for the support of external volumes.
