### ISSUE TITLE
Unable to Migrate Playlist Content

### ISSUE THREAD

**Issue by torrinba** [phauer/migrate-itunes-to-rhythmbox#3]
This sounds like a great project and exactly what I am in need of right now, but I am unable to get it to work.  I am migrating from iTunes 12.5.1.21 into Rhythmbox 3.3 both of which I believe are supported.  I have your code installed (only installation warnings were for depreciates) and I am able to run it.  However, when I follow the instructions for migrating playlists, all I get are the playlist names, but all are empty.  This seems like good evidence that the paths for the iTunes library and target Rhythmbox playlists are correct.  All of the music has been added to Rhythmbox already and --target_library_root is set as the root path to where the music currently resides.  So the only variable I am unsure about is --source_library_root.  I presume that this is supposed to be the old path to where the music used to reside when it was in iTunes and as such I am setting it to C:/Users/(username)/Music/iTunes/iTunes%20Media/Music/ which is typically the default for iTunes on Windows.  Is this all correct?  If so what could be going wrong?

Thanks for your help

EDIT: I didn't realize that angle brackets make text disappear in this chat box.

**Comment by phauer** [comment]
Hi bechtt,
The opposite is true: empty playlists is a good evidence that the paths are not correct.
I spot two slashes after "Users" in `C:/Users//Music/iTunes/iTunes%20Media/Music/`. Try to remove one.

**Comment by phauer** [comment]
Hi bechtt,
The opposite is true: empty playlists is a good evidence that the paths are not correct.

How do the song paths look like in iTunes (`iTunes Music Library.xml`) and in Rhythmbox (`~/.local/share/rhythmbox/rhythmdb.xml`)?

**Comment by torrinba** [comment]
Thanks for the quick response!

A line containing song paths in the iTunes library has the form:
`<key>Location</key><string>file://localhost/C:/Users/(username)/Music/iTunes/iTunes%20Media/Music/(songname).mp3</string>`

And in Rhythmbox:
`<location>file:///home/(username)/Music/(songname).mp3</location>`

EDIT: Of course angle brackets are a problem with these also... using markdown brackets now

**Comment by phauer** [comment]
Looks normal. And what are your values for target_library_root and source_library_root?

Can you give me a path in the created playlists.xml (for rhythmbox)? They will probably not match to the one in your rythmdb.xml.

**Comment by torrinba** [comment]
So I started watching the playlists.xml files I was creating.  They had all the songs in them initially, but when I opened Rhythmbox to check if the migration had worked, they would be deleted from the playlists.xml file, leaving only the playlist names behind.  In this process all I did was push the up arrow from the command terminal to execute the same migrate-itunes-to-rhythmbox playlists that I had already been running but eventually it worked... I'm not sure what could have possibly changed in Rhythmbox, but it was suddenly able to find the songs and populate the playlists.  Perhaps it wasn't finding all of my music before for some reason, but it seems unlikely that your problem was the real culprit.

Many thanks for debugging this with me!

**Comment by phauer** [comment]
Two slashes are missing in `file:/home/...`. It should be `file:///home/...`. But your input files and parameters look fine. Can't say why this happens.
Can you attach a (minimal) itunes-library.xml and rhythmdb.xml that produce this behavior, please? So I can reproduce it.

**Comment by phauer** [comment]
Two slashes are missing in `file:/home/....` It should be `file:///home/....`. Your input files and parameters look correct.

Anyway, I'm glad, that it finally worked out. You're welcome!
I'll add a troubleshooting section in the README and cover tips for debugging.

**Comment by torrinba** [comment]
Sorry the missing slashes were a typo.  Just to put this to rest here is the command that I used:
`migrate-itunes-to-rhythmbox playlists --itunes_library_xml="~/iTunes/iTunes Music Library.xml" --rhythmbox_playlists_xml="~/.local/share/rhythmbox/playlists.xml" --source_library_root="C:/Users/(username)/Music/iTunes/iTunes%20Media/Music/" --target_library_root="/home/(username)/Music/"`

And here is one of the output lines in playlists.txt:
`<location>file:///home/(username)/Music/(songname).mp3</location>`

I think a troubleshooting section would be an excellent addition to the README.  One detail in particular that would be nice to have is a better description of how to set the --source_library_root and --target_library_root variables.  This was a bit unintuitive for me since neither actually points to the *.xml library but instead to the directory where music files reside.  It also seems that the structure of the source_library_root and target_library_root have to match for the migration to work.  This could conceivably be an issue for someone that has restructured their music during the move.  I could also easily see someone migrating from an old operating system, like myself, not remembering the path to their music files on the old machine and knowing how it can be found in the iTunes library file was definitely helpful.

Anyway I think this is a great piece of code for migrating music libraries.  Thanks for all the work you have put in!

**Comment by phauer** [comment]
You're welcome!
I added a troubleshooting section. Does this help to clarify the usage of the parameters?

**Comment by torrinba** [comment]
Yes, the troubleshooting section sounds very helpful for setting the parameters.  Thanks again!
