### ISSUE TITLE
Version compatibility update

### ISSUE THREAD

**Issue by tanvil** [phauer/migrate-itunes-to-rhythmbox#6]
Successfully migrated 120 playlists and counts/ratings for a 5000 song library from iTunes 12.5.4 to Rhythmbox 3.4.1 on Ubuntu Mate 16.10.

Thanks for your effort on this, you did a great job. Really appreciate it!

**Comment by phauer** [comment]
Hi tanvil! I'm so glad about your kind words and your update regarding the version numbers! Thanks!
