### ISSUE TITLE
insatllation errors

### ISSUE THREAD

**Issue by kkrois** [phauer/migrate-itunes-to-rhythmbox#9]
during installation i get 2 errors:

1)
 DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.

2)
Error [Errno 2] Datei oder Verzeichnis nicht gefunden: 'git' while executing command git clone -q https://github.com/phauer/pyitunes.git /tmp/pip-build-7owa7wzq/pyItunes
Cannot find command 'git'

What can i do?

Also i get the message: "You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."
When executing 'pip install --upgrade pip' i get "Requirement already up-to-date"

ciao ><

**Comment by phauer** [comment]
Hi kkrois, 
1: it's just a warning. you can ignore it.
2: git is not installed on your machine. Install it and it should work. `sudo apt install git` (if you are using ubuntu/debian).
3: Again, only a warning. Feel free to update pip.

Cheers, Philipp

**Comment by kkrois** [comment]
Hi Philipp,
thank you for the prompt answer. It helped :)
ciao ><

**Comment by phauer** [comment]
You're welcome

**Comment by dushoff** [comment]
On ubuntu 18.04. python3 version 3.6.8. Installed pip. On the pip3 install step, got: 
   fatal error: libxml/xmlversion.h: No such file or directory
Tried installing python3-libxml2 on a hunch. Did not help.

**Comment by dushoff** [comment]
Solved: 
   apt install libxml2-dev libxmlsec1-dev
